################################
### DO NOT EDIT THIS FILE!!! ###
################################

# This script will cause OpenC3 COSMOS to receive 1 STATE_OF_HEALTH packet for the HEALTH_MONITOR target.
# Screens that reference the HEALTH_MONITOR target's STATE_OF_HEALTH packet will reflect this data and any derived items.
#
# Expected Behavior:
#   - TEMPERATURES_STATE should reflect that the worst-state _TEMP telemetry item is GREEN
#   - VOLTAGES_STATE should reflect that the worst-state _VOLTAGE telemetry item is YELLOW
#   - CURRENTS_STATE should reflect that the worst-state _CURRENT telemetry item is RED

set_line_delay(0.0001)

require 'openc3'
require 'openc3/script'

# Temps
CAMERA_TEMP_GREEN = 35
CAMERA_TEMP_YELLOW = 53
CAMERA_TEMP_RED = 65

BATTERY_STACK_TEMP_GREEN = 35
BATTERY_STACK_TEMP_YELLOW = 53
BATTERY_STACK_TEMP_RED = 65

RADIO_TEMP_GREEN = 35
RADIO_TEMP_YELLOW = 53
RADIO_TEMP_RED = 65

# Voltages
CAMERA_VOLTAGE_GREEN = 4950
CAMERA_VOLTAGE_YELLOW = 5700
CAMERA_VOLTAGE_RED = 6000

BATTERY_STACK_VOLTAGE_GREEN = 7600
BATTERY_STACK_VOLTAGE_YELLOW = 8650
BATTERY_STACK_VOLTAGE_RED = 8800

RADIO_VOLTAGE_GREEN = 4950
RADIO_VOLTAGE_YELLOW = 5700
RADIO_VOLTAGE_RED = 6000

# Currents
CAMERA_CURRENT_GREEN = 1000
CAMERA_CURRENT_YELLOW = 1500
CAMERA_CURRENT_RED = 2200

BATTERY_STACK_CURRENT_GREEN = 26000
BATTERY_STACK_CURRENT_YELLOW = 30000
BATTERY_STACK_CURRENT_RED = 32000

RADIO_CURRENT_GREEN = 100
RADIO_CURRENT_YELLOW = 1100
RADIO_CURRENT_RED = 1400

inject_tlm( "HEALTH_MONITOR",
            "STATE_OF_HEALTH",
            {
                "ERROR_CODE" => (1).to_i,
                "TIMESTAMP" => (Time.now).to_i,
                "CAMERA_TEMP" => CAMERA_TEMP_GREEN,
                "BATTERY_STACK_TEMP" => BATTERY_STACK_TEMP_GREEN,
                "RADIO_TEMP" => RADIO_TEMP_GREEN,
                "CAMERA_VOLTAGE" => CAMERA_VOLTAGE_GREEN,
                "BATTERY_STACK_VOLTAGE" => BATTERY_STACK_VOLTAGE_YELLOW,
                "RADIO_VOLTAGE" => RADIO_VOLTAGE_YELLOW,
                "CAMERA_CURRENT" => CAMERA_CURRENT_RED,
                "BATTERY_STACK_CURRENT" => BATTERY_STACK_CURRENT_RED,
                "RADIO_CURRENT" => RADIO_CURRENT_RED,
            })
